<?php

//##############################################################################
//
// main home page for the site 
// 
//##############################################################################
include "top.php";

// Begin output
print '<article>';
print '<h2>The Wonder of Florence</h2>';?>
<div>
        <p id="intro">Narrative by Nicholas Thompson : <b>The book Brunelleschi’s Dome is by Ross King </b> who writes about one of the first Renaissance geniuses of the time, who improves and reinvents architecture. 
            On August 19, 1418, the “Opera del Duomo” or the office of works in Florence announced a competition to everyone, that a model was needed for the vaulting of the main Dome for the cathedral, Santa Maria del Fiore. The competition would last until the end of September and the winner would be awarded 200 Florins (pg. 1). The payment of 200 Florins was a fair sum of money, more than a skilled carpenter or goldsmith could make in two years of salary (pg. 1). The payment is what attracted people all across Tuscany to build models for the Domes construction. The competition was not only used to determine the design of the Dome, but find a solution to the many architectural problems that would occur if a Dome so grand was to be built. The original plan for the cathedral did not provide an answer, architects during that time misunderstood the forces of gravity, and many Domes had fallen because people had trusted in God to find a solution. The “Opera del Duomo” was the backbone of the project and had funded its construction since the 1330s (pg. 6), and none of them wanted to see their wealth put to waste, so they held competitions to appoint architects and an architect-in-chief to design and direct masons on the construction.</p>
        <p>Before the competition of 1418, the man Filippo Brunelleschi had lived his young life in San Giovanni, which is west of the cathedral. Filippo’s father was named Ser Brunellesco, he worked as a civil servant during his lifetime and wished that his son could follow his footsteps. However, Filippo had more of an interest in mechanics and solving problems. Since Filippo lived most of his young life near the Santa Maria del Fiore, he developed an interest in the cathedrals construction and what machines aided the builders in transporting the marble or sandstone to incredible heights. Filippo’s father agreed to let his son follow his own wishes and at age fifteen Filippo was apprenticed to a goldsmith. Apprenticeship to a goldsmith allowed Filippo to discover a large variety of talents in order to develop as an artist. Filippo became a master goldsmith in 1398, when he was at the age of twenty-one (pg.13). At the same time, he had also begun to study motion, dealing with weights, wheels and gears. </p>
        <p>Only three years later Filippo was involved in his first competition and rivalry. The Guild of Cloth Merchants introduced a competition that demanded a model for the new set of bronze doors for the Baptistery of San Giovanni. The old doors on the Baptistery were from the 1330s and had gone through disrepair because of the Black Death, which had killed twelve thousand natives of Florence in just the summer of 1400 (pg. 15). By commissioning a new set of bronze doors, the Guild of Cloth Merchants sought to please god and revoke their sins, in order to prevent another plague. However, the Black Death was not the only crisis in Florence. Florence was also faced with the threat of war. The duke of Milan or Giangaleazzo Visconti was an old enemy of Florence and by 1401, he ruled all of northern Italy (pg. 16). Giangaleazzo put Florence at a standstill by installing a siege at the city’s gates and cutting off all the supplies and resources. The Santa Maria del Fiore construction had to cease during this time because other close by cities were in need of fortifications, to prevent the duke of Milan from them taking over. However, the competition for the baptistery doors did not cease. The requirement for these doors was that each person had to illustrate their own version of Abraham’s sacrifice of Isaac and complete their doors in a year’s time (pg. 17). </p>
        <p>In a year, everyone’s model was completed and out of the seven people, only two were considered for the project. Filippo Brunelleschi and Lorenzo Ghiberti were claimed victors and it was decided that they should work in collaboration to accomplish the project. However, Filippo disliked this idea because he would rather work in secrecy and he did not know if he could trust Lorenzo because his personality was very different. Filippo was also afraid of plagiarism and did everything he could to hide his ideas by ciphering it into a code. Filippo dropped out of the competition and went to Rome for a little more than a decade, where he would study the Roman ruins. During that same year, the siege upon Florence was lifted because the duke of Milan, Giangaleazzo Visconti had died that summer from an illness. Florence was now free from the tension and could once again commence building the cathedral, Santa Maria del Fiore. </p>
        <p>When Filippo took off for Rome, he also brought with him a young sculptor named Donatello, the two were alike and that made it easier for Filippo to analyze the ruins and learn from them. Filippo and Donatello went from place to place and did not care about themselves, they only wanted to search for ruins and artifacts. Rome was in shambles, from the earthquakes, the endless wars, and the lack of trade or industry. Only tourists or pilgrims visited Rome with a copy of “the wonders of Rome” (pg. 22), a guide that did not lead pilgrims to Roman remains, but instead to the Christian relics. As for the Roman remains, they were left to the elements and everyone neglected their importance, except Filippo and his partner named Donatello. They collected Roman rubble and were known as ‘treasure hunters’ (pg. 24). While collecting and observing Roman artifacts, Filippo developed a series of cryptic symbols and Arabic numbers. This was used to conceal discoveries to any jealous rival.</p>
        <p>Filippo’s main goal in surveying the Romans ruins was to learn from them. When he calculated the proportions of columns, he was able to determine the proper architectural orders implied by the Greek and Romans. (Doric, Ionic, Corinthian) (pg. 26). He also could have looked at the vaulting methods of the Romans to understand their ways of constructing a Dome. For instance, The Golden House of Nero provided an example for the octagonal shape of the Dome for Santa Maria del Fiore. Even if the Dome in Florence would be much larger than this example in Rome (only a span of 35 feet), it still shows that it is possible to build one in that fashion. Another example Filippo could have taken interest in is the Pantheon. This temple was built during the Emperor Hadrian’s time and has a colossal span of 142 feet and a rise of 143 feet (pg. 27). This Dome exists still in Rome and is a perfect hemisphere, however, it does contain visible cracks along its inside and the Romans tried to counter this stress by making its concrete walls 23 feet of thickness (pg. 27). The cracks were caused by hoop stress, which is the outward motion of the Dome after it is completed. The 23 feet of thickness could not even counter the Pantheon’s hoop stress. This was a common occurrence with concrete built Domes and the Pantheon’s visible cracks told Filippo that it was very important to construct a stable Dome on a stable foundation.</p>
        <p>One or two years before the competition in 1418 for the model for the Dome of Santa Maria del Fiore, Filippo came back from Rome with an invaluable understanding about vaulting techniques. However, Filippo had not yet developed much of a reputation since being away in Rome. He was soon to gain more respect by the year 1418, when he not only joined the competition, but also painted an optical illusion. Filippo is considered the inventor of perspective, and the reason for this can be directed to his surveying of Roman ruins (pg. 35). Filippo painted an image of the Baptistery of San Giovanni, then for the sky, he put burnished silver to act as a mirror that would reflect the sky above, and afterward he inserted a small hole where the vanishing point would be. When the painting was finished, it was ready for the observer. To look at the painting a person would turn the painting away from himself and look through the hole or vanishing point. A person would then, in the other hand, hold a mirror in front of the painting to reflect the painting and when a person looked through the hole, he could see a lifelike image of the Baptistery of San Giovanni. Filippo’s painting was so detailed that many observers thought it was a real image instead of a painting. Now that Filippo had given the impression he wanted over people, soon after he would join the competition to build a model for the Dome of Santa Maria del Fiore in 1418.</p>
        <p>Filippo quickly came to the challenge of building a model for the competition in 1418. The main reason for this competition was to solve the earlier competition model of 1367 that demanded invisible supports. A man named Neri di Fioravanti came up with this model in 1367 because he was opposed to a traditional Gothic style church, which had been built, by most of Florence’s enemies, Germany, France and Milan (pg.7).  Neri di Fioravanti was able to find a probable solution; he claimed that the Dome could be held up by multiple wooden and stone chains that would run all the way up the walls where hoop stress was most likely. However, Neri’s idea was hard to comprehend for everyone and there was controversy over supports that would hold the Dome in place during construction. The competition of 1418 would hopefully answer the questions of doubtful Florentines. </p>
        <p>Many people expected Filippo to find a clever solution to the controversy of 1367, the question of using what technique to support an octagonal shaped Dome.  Filippo’s model was constructed with bricks and was the size of a small building, it big enough for people to walk through inside and analyze his work (pg.40). The model also had final additions put on it by artists like Filippo’s old friend Donatello, who made carvings on the models walls. However, there was no need to rush in building this model, because the Opera extended the time available for the competition to December (pg. 40). On the day of inspection, the onlookers were fairly surprised and unconfident about Filippo’s different way of assembling a Dome. Filippo did not use the centering technique that involved wooden supports to keep the masonry from collapsing. Filippo was so confident in himself that he refused to share his ideas about this matter with anyone, he was also afraid of plagiarism. Even if Filippo did not share his plans with the Opera’s commission, he still won them over and was named architect-in-chief of the project. The way Filippo won the competition and convinced the Opera for his technique can be explained with a quote in the book; “In this parable Filippo suggests to the wardens that whoever can make an egg stand on end on a flat piece of marble should win the commission. When all of the other contestants fail the test, Filippo simply cracks the egg on the bottom and then stands it upright. When his rivals protest that they might have done the same, Filippo retorts that they would know how to vault the cupola, too, if only they knew his plans.” (pg. 42).</p>
        <p>Once construction of the Dome was prepared, the only thing that still needed assurance was the masons and the Opera who were both quite nervous about Filippo’s plan for building the Dome. However, the Opera did not total rely on Filippo to plan the build, the Opera installed a program with Filippo on how to construct the Dome without centering (pg. 52). The Opera agreed with Filippo that each shell of the Dome would be built up to 57 feet without support, which was a crucial point where collapse of the Dome could be immanent. In order to prove himself, Filippo had to devote himself to this task so he could convince the Opera of building the whole Dome without centering. </p>
        <p>After the task of convincing the Opera, Filippo would also devote himself to many more daunting questions in order to solve and build the Dome of Santa Maria del Fiore. Many machines where used when building the Dome, but some were outdated and could no longer sustain the heavy loads of stones that needed to be delivered at the increasing height of the Dome. Filippo would now devote himself to building several more machines that would replace the old and allow the Dome’s work to proceed faster. Out of this devotion came an innovative ox-hoist that could raise a load of 1,000 pounds to a height of 200 feet with one ox in just 13 minutes (pg. 61). The Opera was very pleased with the ox-hoist and awarded Filippo a sum of a 100 Florins (pg. 65). With the success and popularity Filippo had now gained from the ox-hoist, he would now build another machine that was needed to replace an old crane. The new crane was built in a short time and was fitted with a special turnbuckle that could move loads from the ox-hoist across to their destination (pg. 68). After these two machines were built Filippo would now have to design the first chains for the Dome that Neri di Fioravanti had planed in 1367.</p>
        <p>There were other factors besides inventing machines and designs for the Dome that Filippo had to pay close attention to and avoid structural damage or endangering workers’ lives. Filippo had to calculate the horizontal rise of the Dome and make sure everything was even and fit into place (pg. 83). Filippo had to direct the masons and have them build the Dome at the same time on each side so that the calculations could be made and error could be corrected if one side was at fault. By remembering to calculate the horizontal rise of the Dome, Filippo was able to prove to the Opera that no centering or supports for the Dome were ever needed. Another thing that Filippo had to pay close attention to was the bricks and mortar being used everyday. Filippo knew it was very crucial that everything about the bricks and mortar had to be of the best of quality and be laid properly. In order to keep the building at a normal pace, Filippo inspected the masons while they constructed the Dome. Filippo was no lazy man and was always busy with something that benefited the Dome’s construction.</p>
        <p>Filippo kept up with the pace and kept building and designing for the Opera until the Dome’s construction was completely finished. His determination and skill as an architect is demonstrated by the span and height of the Dome that remained unequalled until the 20th century (pg. 163). Once the Dome itself was finished, the lantern had to be designed and put on top of the Dome as the final touch.  Sadly, Filippo only lived long enough to see the first stone of the lantern consecrated by the new archbishop in 1446 (pg. 153).</p>
        <p>Although Filippo was gone, an additional enhancement was added to the dome under the loyal guidance of his long-time friend, Paolo Toscanelli, one of the greatest mathematicians and astronomers of the century. Toscanelli installed a bronze plate at the base of the lantern. This plate reflected the sun’s rays through the lantern to the floor of the cathedral where a sundial, in the form of a cross was located. This ingenious device would enable Toscanelli to make more accurate calculations of the summer solstice and vernal equinox, and set religious holidays. These calculations ultimately contributed to the revising of the Alfonsine tables and thus permitted navigators to plot course positions more accurately (pg. 149). This precision led to the exploration and mapping of the new world.</p>
        
        <p>Go to the <a href="form.php">People</a> link above to view information on the key characters.</p> 

        <figure>
            <img src="images/amazon.jpg" alt="dome pic">
            <br />
            <figcaption>Brunelleschi’s Dome by Ross King. Image taken from <a href="http://ecx.images-amazon.com/images/I/51t%2Bw-%2B7-bL._SY344_BO1,204,203,200_.jpg" target="_blank">Amazon</a></figcaption>
        </figure>

        
</div>
<?php
print '</article>';
include "footer.php";
?>